
#' Generating random treatment assignments
#'
#' @description Generates random treatment assignments from a specified logistic model
#'
#' @param formula an object of class \code{"formula"}, a symbolic description of the model
#' for the logistic model for treatment assignments (the propensity model)
#' @param data data.frame of covariates for propensity model
#' @param beta vector of covariate effects for the logistic propensity model. Must be equal
#' in length to the design matrix generated by the specified \code{formula}
#' @param indep logical value. If \code{FALSE} the treatment assignments will be generated by
#' the model specified by \code{formula}; if \code{TRUE}, treatment assignments will be generated
#' indepenedently of any covariates, with the treatment taking value \code{1} on average
#' \code{trt.frac} * 100 percent of the time. User must specify the sample size via
#' \code{n} if \code{indep = TRUE}.
#' @param trt.frac fraction (between 0 and 1) of treatment values that take value \code{1}
#' @param n positive integer value for sample size. Must be specified if \code{indep = TRUE}.
#' @importFrom stats model.matrix glm binomial
#' @export
#' @examples
#'
#' x <- gen_covariates(50, p.contin = 6, p.binary = 4, rho = 0.9, bin.prob = 0.25)
#'
#' beta <- gen_coefs(11, nonzero.frac = 0.85,
#'                   max.effect.size = 0.25)
#'
#' trt <- gen_trt(~ ., data = data.frame(x), beta = beta)
#'
#' trt
#'
#' summary(glm(trt ~ x, family = binomial()))
#'
#' trt <- gen_trt(indep = TRUE, trt.frac = 0.25, n = 500)
#'
#' table(trt) / length(trt)
#'
gen_trt <- function(formula,
                    data,
                    beta,
                    indep = FALSE,
                    trt.frac = 0.5,
                    n)
{

    indep <- as.logical(indep[1])

    if (indep)
    {

        n <- as.integer(n[1])
        stopifnot(n > 0)
        trt.frac <- as.double(trt.frac[1])
        stopifnot(trt.frac >= 0 & trt.frac <= 1)

        trt <- rbinom(n, 1, trt.frac)
    } else
    {
        x <- model.matrix(formula, data = data)
        p <- NCOL(x)
        if(length(beta) != p) stop("Length of beta must equal the dimension of the design matrix generated by
                                    specified formula (accounting for any intercept too).")

        prob <- 1 / (1 + exp(-drop(x %*% beta)))

        trt <- rbinom(NROW(x), 1, prob)
    }

    trt
}
